apiVersion: v1
data:
  password: >-
    ENC[AES256_GCM,data:z1nr2QEVdlXokJ5NOPtDrzNIfeLzyyxb,iv:n+RxZbMHp0ZmDV3xgZuvfuzEVXeeouU7GsT1NxZuWB8=,tag:Zj635Ci6iB1PVuHNmJLs3Q==,type:str]
  username: >-
    ENC[AES256_GCM,data:9m20/y2zDZIK5qaTD6O/AJ82gaRXn0aU,iv:qVhWm43fpViTudaASDqAi9D2B+zxvkzHkawDNIWCVN0=,tag:BiIRxV1qJbKxJM7u9eJ1yQ==,type:str]
immutable: false
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    test: test
  name: my-db-secret
  namespace: default
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZ1ZZRCs1OHZhYlJESkxs
        OVJXYk9ROEJ4WWVZTHl2bnA3NFZVUHVpbGpzCjI4elNFQnRXYUdONnFKSktrTjdp
        TkM0aWR1RnVNK1ZCODlRR2RyUU5Uam8KLS0tIEcrNjlTaXo2WnFNODh3ZmU1TU83
        TUY0NXJSMU5zaUdaOGtsNzlCTzExU3MKCIFsZiiSD0YA0MgIEm1wzDuhhj5BcVW7
        LzFl0t8r0K9NK5Zk9NzC2bk9CLtaCtCls0plA2ZaTrQ0RfJFI7L4yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f7h9wdfwxlj3pdx8lg6fueeq5948drpuwp0j93sryahuayfvu5msn7ect5
  azure_kv: null
  encrypted_regex: ^(data|stringData)$
  gcp_kms: null
  hc_vault: null
  kms: null
  lastmodified: '2023-03-09T15:26:11Z'
  mac: >-
    ENC[AES256_GCM,data:YASXkfKTl6Zw8DC1XsacsDgB2F7A/B0SmmfhN+Lyau5D0op/d4kTAiVI6CV2u6XzqwgaBln/fTIT/UQhEuC4L/lPTFz5djaCwSZA9lZuFmN7KmvE3lBrbU+uwz2nzdhSBzw4Xx+nioYpyg00gMnlg4kJbCyU5FXSg9fQUjqqadA=,iv:f2XOBK91HzoJhssuNJ2Yklqe7Wl9JW7XWxDoT9JPegw=,tag:N+IoELZdxg85mqUxRQONGg==,type:str]
  pgp: null
  version: ''
type: Opaque
