apiVersion: v1
data:
  password: >-
    ENC[AES256_GCM,data:N4vrEg==,iv:TC8jWdT4QJBjmV1yhZcQ9YtCKZfr75W1eZ7US9yD5Zk=,tag:qnYEddcEg7a3xN9Tcn484w==,type:str]
  username: >-
    ENC[AES256_GCM,data:G73wyQ==,iv:msDzypuhzJR6iZrZWBcdZaSpyFCkdEkNIjaHH1n9js4=,tag:MTNLG2nzizBxrq8WehrojA==,type:str]
immutable: false
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    test: test
  name: my-db-secret
  namespace: default
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdnhIclRkOW1hZ0NHMzVZ
        bmFRRTUwS3dyOW95RVE0YllSZnhqMi9Qa0hRCmgrbE5UbGlBM1VUYTk4SlR0a1Yz
        dmFDUEo5ODhkRUlVV1A4eGRlRm96Nk0KLS0tIHdZWDB3eHdQMi9WSU5VVFdidmVu
        UEttTko5YXltS2VoR0U4cVJMWUttaVkKC2YVlPEPt5fNnIBX8DD+jUmbrpsm0B0o
        kWhbIqfcbWzuKBamxpFB2m37GbrKMfMFrs8Hjr6gZbGIu3Us3W5inQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f7h9wdfwxlj3pdx8lg6fueeq5948drpuwp0j93sryahuayfvu5msn7ect5
  azure_kv: null
  encrypted_regex: ^(data|stringData)$
  gcp_kms: null
  hc_vault: null
  kms: null
  lastmodified: '2023-03-09T15:09:19Z'
  mac: >-
    ENC[AES256_GCM,data:F7BurqSNnc++BRybbVnWp39Q+MMLi+CzpRrHJeAbp9gRfDlgGu/dvL6eLpz7fKLUpywPUzduRf09TX8VUGO/XOfTito7AyKU2D+rSJRU9Wqmc8tp9RJHTgLpKyOTzEOQXCZ5g8LmIm9JoC6IUPYmYk+hlWIHKVP2eXUl6Poe+Nc=,iv:khDRpXgPAej4f0HvIDouTwj7N29iFJh4UKaeQMQkw1o=,tag:vXxQWndt6jT5UKCOOzVnWw==,type:str]
  pgp: null
  version: ''
stringData:
  password: >-
    ENC[AES256_GCM,data:ygYb66Y=,iv:fnmNMpIEcddurHesjHTcKDdSFTK9jXWWfN03EN6xU7Q=,tag:r+rPHD9OkZ6XmQLKqhvQeg==,type:str]
  username: >-
    ENC[AES256_GCM,data:l7c7xmE=,iv:wB5EIk3AEizUNMZRau6rhznbhwoF9jBa5swIaw0ShYM=,tag:cpSMnoIeaYhS+l1IOzjgfQ==,type:str]
type: Opaque
